### ISSUE TITLE
Kustomization migration assumes git creds is needed

### ISSUE THREAD

**Issue by christianh814** [christianh814/mta#6]
Given the following `GitRepository` and `Kustomization`...

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-examples
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/christianh814/gitops-examples
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: welcome-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./welcome-k8s/overlays/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-examples
```

The following command will fail

```shell
$ mta kustomization --name welcome-app
FATA[0000] gitrepositories.source.toolkit.fluxcd.io "welcome-app" not found 
```

This is because `mta` [currently assumes that all repos require authentication](https://github.com/akuity/mta/blob/main/cmd/kustomization.go#L112)

This should be changed to check to see if the `Kustomization` is using a public repo.
